[package]
name = "pg-schema-diff"
version = "0.0.1"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"

[dependencies]
colored = "2.0.0"
indexmap = "1.6.1"
postgres-parser = "0.2.0"
rand = "0.8.0"
# postgres-parser = { path = "../postgres-parser" }